export default {
    'login': 'ورود',
    'logout': 'خروج',
    'register' : 'ثبت نام',
    'profile' : 'حساب کاربری',
    'forgot_password':'بازیابی رمز عبور',
    'username' : 'نام کاربری',
    'password' : 'رمز عبور',
    'repassword' : ' تکرار رمزعبور ',
    'recovery' : 'بازیابی رمز عبور',
    'email' : 'ایمیل',
    'avatar' : 'تصویر',

    'login_success' : 'خوش آمدید.',
    'login_failed' : "شماره تلفن یا کلمه عبور صحیح نمی باشد.",
    'login_account_disabled' : "حساب کاربری شما غیرفعال می باشد.",
    'login_account_blocked' : "حساب کاربری شما مسدود می باشد.",
    'logout_success' : 'با موفقیت خارج شدید.',
    'lastName' : 'نام خانوادگی',
    'firstName' : "نام",

    'no_access' : "برای دسترسی به پنل مدیریت باید ابتدا وارد شوید.",
    'already_user' : 'کاربر قبلا ثبت نام شده است.',
    'not_already_user' : 'کاربری با این مشخصات یافت نشد',
    'already_reset_key' : 'قبلا برای بازیابی رمز درخواست داده اید لطفا پس از دو دقیقه درخواست مجدد بدهید',

    'validation' : {
        'email_required' : 'وارد کردن ایمیل الزامی است!',
        'phone_required' : 'لطفا شماره تلفن را برای من ارسال کنید',
        'firstName_required' : 'وارد کردن نام الزامی است!',
        'lastName_required' : 'وارد کردن نام خانوادگی الزامی است!',

        'email_format' : 'ایمیل نامعتبر است!',
        'password_required' : 'وارد کردن رمزعبور الزامی است!',
        'pass2_required' : 'وارد کردن رمزعبور جدید الزامی است!',
        'pass3_required' : 'وارد کردن تکرار رمزعبور جدید الزامی است!',
        'pass3_not_mach' : 'تکرار رمز عبور جدید مطابقت ندارد.',
        'dayMode_invalid' : 'مقدار وارد شده برای حالت روز و شب نامعتبر است',
        'soundMode_invalid' : 'مقدار وارد شده برای افکت صوتی نامعتبر است',
    },
    'update_profile_success' : 'مشخصات شما با موفقیت ویرایش شد.',
    'duplicate_email' : 'ایمیل تکراری است.',
    'update_profile_currentPass_not_valid' : 'رمز عبور فعلی اشتباه است.',
    'profile_hint_password_change' : 'اگر نمیخواهید رمز عبور خود را تغییر بدهید فیلدهای زیر را خالی بگذارید.',
    'avatar_already' : 'تصویر کاربر قبلا انتخاب شده است.',
    'file_required' : 'لطفا فایل مورد نظر را انتخاب نمایید.',
    'update_avatar_success' : 'تصویر آواتار با موفقیت ویرایش شد.',
    'update_avatar_faild' : 'مشکل در آپدیت تصویر آواتار.',
    'avatar_not_exist' : 'تصویری برای آواتار انتخاب نشده است.',
    'user_not_found' : 'کاربر یافت نشد!',
    'password_sms_send' : 'رمزعبور یک بار مصرف برای شما پیامک شد.',
    'sms_password_is_already' : 'قبلا رمزعبور برای شما پیامک شده است لطفا دقایقی بعد تلاش کنید.',
    'phone_is_invalid' : 'کاربری با این شماره تلفن یافت نشد.',
    'duplicate_phone' : 'شماره تلفن وارد شده تکراری است.',
    'user_has_not_access_this_panel':'شما دسترسی به این پنل ندارید.',
    'sso_service_connection_error' :'مشکلی در درگاه مرکزی وجود دارد لطفا بعدا تلاش کنید',
    'can_not_change_your_role' : 'شما نمیتوانید نقش خودتان را تغییر دهید',
    'too_many_nationalIds': "تعداد شماره ملی ها نباید بیشتر از ۱۰۰ کاربر باشد."
}